/*
 * Copyright © 2025 Paul Tavitian.
 */

export const occupancies = {
  filenameBase: 'occupancies',
  filenameExtension: 'txt',
  nonstandard: true,
  schema: [
    {
      name: 'id',
      type: 'integer',
      primary: true,
      index: true,
    },
    {
      name: 'trip_id',
      type: 'text',
      required: true,
      index: true,
    },
    {
      name: 'stop_sequence',
      type: 'integer',
      min: 0,
      index: true,
    },
    {
      name: 'occupancy_status',
      type: 'integer',
      min: 0,
      max: 6,
      index: true,
      required: true,
    },
    {
      name: 'monday',
      type: 'integer',
      required: true,
      min: 0,
      max: 1,
      index: true,
    },
    {
      name: 'tuesday',
      type: 'integer',
      required: true,
      min: 0,
      max: 1,
      index: true,
    },
    {
      name: 'wednesday',
      type: 'integer',
      required: true,
      min: 0,
      max: 1,
      index: true,
    },
    {
      name: 'thursday',
      type: 'integer',
      required: true,
      min: 0,
      max: 1,
      index: true,
    },
    {
      name: 'friday',
      type: 'integer',
      required: true,
      min: 0,
      max: 1,
      index: true,
    },
    {
      name: 'saturday',
      type: 'integer',
      required: true,
      min: 0,
      max: 1,
      index: true,
    },
    {
      name: 'sunday',
      type: 'integer',
      required: true,
      min: 0,
      max: 1,
      index: true,
    },
    {
      name: 'start_date',
      type: 'integer',
      required: true,
      index: true,
    },
    {
      name: 'end_date',
      type: 'integer',
      index: true,
    },
    {
      name: 'exception',
      type: 'integer',
      min: 0,
      max: 1,
      index: true,
    },
  ],
};
