export const stops = {
  filenameBase: 'stops',
  filenameExtension: 'txt',
  schema: [
    {
      name: 'stop_id',
      type: 'text',
      primary: true,
      required: true,
      prefix: true,
      index: true,
    },
    {
      name: 'stop_code',
      type: 'text',
      index: true,
    },
    {
      name: 'stop_name',
      type: 'text',
      nocase: true,
      index: true,
    },
    {
      name: 'tts_stop_name',
      type: 'text',
      nocase: true,
      index: true,
    },
    {
      name: 'stop_desc',
      type: 'text',
      nocase: true,
      index: true,
    },
    {
      name: 'stop_lat',
      type: 'real',
      min: -90,
      max: 90,
      index: true,
    },
    {
      name: 'stop_lon',
      type: 'real',
      min: -180,
      max: 180,
      index: true,
    },
    {
      name: 'zone_id',
      type: 'text',
      prefix: true,
      index: true,
    },
    {
      name: 'stop_url',
      type: 'text',
      index: true,
    },
    {
      name: 'location_type',
      type: 'integer',
      min: 0,
      max: 4,
      index: true,
    },
    {
      name: 'parent_station',
      type: 'text',
      index: true,
      prefix: true,
    },
    {
      name: 'stop_timezone',
      type: 'text',
      index: true,
    },
    {
      name: 'wheelchair_boarding',
      type: 'integer',
      min: 0,
      max: 2,
      index: true,
    },
    {
      name: 'level_id',
      type: 'text',
      prefix: true,
      index: true,
    },
    {
      name: 'platform_code',
      type: 'text',
      index: true,
    },
  ],
};
