export const stopTimes = {
  filenameBase: 'stop_times',
  filenameExtension: 'txt',
  schema: [
    {
      name: 'trip_id',
      type: 'text',
      required: true,
      primary: true,
      prefix: true,
      index: true,
    },
    {
      name: 'arrival_time',
      type: 'time',
      index: true,
    },
    {
      name: 'departure_time',
      type: 'time',
      index: true,
    },
    {
      name: 'location_group_id',
      type: 'text',
      prefix: true,
      index: true,
    },
    {
      name: 'location_id',
      type: 'text',
      prefix: true,
      index: true,
    },
    {
      name: 'stop_id',
      type: 'text',
      required: true,
      prefix: true,
      index: true,
    },
    {
      name: 'stop_sequence',
      type: 'integer',
      required: true,
      primary: true,
      min: 0,
      index: true,
    },
    {
      name: 'stop_headsign',
      type: 'text',
      nocase: true,
      index: true,
    },
    {
      name: 'start_pickup_drop_off_window',
      type: 'time',
      index: true,
    },
    {
      name: 'pickup_type',
      type: 'integer',
      min: 0,
      max: 3,
      index: true,
    },
    {
      name: 'drop_off_type',
      type: 'integer',
      min: 0,
      max: 3,
      index: true,
    },
    {
      name: 'continuous_pickup',
      type: 'integer',
      min: 0,
      max: 3,
      index: true,
    },
    {
      name: 'continuous_drop_off',
      type: 'integer',
      min: 0,
      max: 3,
      index: true,
    },
    {
      name: 'shape_dist_traveled',
      type: 'real',
      min: 0,
      index: true,
    },
    {
      name: 'timepoint',
      type: 'integer',
      min: 0,
      max: 1,
      index: true,
    },
    {
      name: 'stop_note',
      type: 'text',
      index: true,
    },
    {
      name: 'pickup_booking_rule_id',
      type: 'text',
      prefix: true,
      index: true,
    },
    {
      name: 'drop_off_booking_rule_id',
      type: 'text',
      prefix: true,
      index: true,
    },
  ],
};
